### ISSUE TITLE
Cannot parse some change sequences

### ISSUE THREAD

**Issue by agarciadom** [TransformationToolContest/ttc2018liveContest#1]
I have a first version of a Hawk-based solution in my branch, but I cannot complete a full run as it seems that some of the change sequence files cannot be parsed:

```
Tool,View,ChangeSet,RunIndex,Iteration,PhaseName,MetricName,MetricValue
Hawk,Q1,1,1,0,Initialization,Memory,186343448
Hawk,Q1,1,1,0,Initialization,Time,2340853571
Hawk,Q1,1,1,0,Loading,Memory,530025296
Hawk,Q1,1,1,0,Loading,Time,2466271455
Hawk,Q1,1,1,0,Initial,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,0,Initial,Memory,615945976
Hawk,Q1,1,1,0,Initial,Time,521900193
Hawk,Q1,1,1,1,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,1,Updates,Memory,1231708944
Hawk,Q1,1,1,1,Updates,Time,2253234875
Hawk,Q1,1,1,2,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,2,Updates,Memory,1761551392
Hawk,Q1,1,1,2,Updates,Time,1970613506
Hawk,Q1,1,1,3,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,3,Updates,Memory,322976680
Hawk,Q1,1,1,3,Updates,Time,1882900302
Hawk,Q1,1,1,4,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,4,Updates,Memory,860363800
Hawk,Q1,1,1,4,Updates,Time,1763166270
Hawk,Q1,1,1,5,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,5,Updates,Memory,1397750872
Hawk,Q1,1,1,5,Updates,Time,1883368597
Hawk,Q1,1,1,6,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,6,Updates,Memory,1935137912
Hawk,Q1,1,1,6,Updates,Time,1640112882
Hawk,Q1,1,1,7,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,7,Updates,Memory,390391904
Hawk,Q1,1,1,7,Updates,Time,1718574402
Hawk,Q1,1,1,8,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,8,Updates,Memory,954300416
Hawk,Q1,1,1,8,Updates,Time,1592608214
Hawk,Q1,1,1,9,Updates,Elements,"[[404236, 200], [167197, 200], [404315, 190]]"
Hawk,Q1,1,1,9,Updates,Memory,1518208928
Hawk,Q1,1,1,9,Updates,Time,1618519988
Hawk,Q1,1,1,10,Updates,Memory,1518208928
Hawk,Q1,1,1,10,Updates,Time,8689469
2018-06-26 11:52:03 [main] ERROR Launcher - Internal error: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Unresolved reference '//@changes.5/@sourceChange/@addedElement/407640'. [file:/home/antonio/src/ttc2018liveContest/models/1/change10.xmi, 33, 297]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.handleErrors[XMLLoadImpl.java:77]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load[XMLLoadImpl.java:185]
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad[XMLResourceImpl.java:261]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load[ResourceImpl.java:1518]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load[ResourceImpl.java:1297]
	at org.eclipse.epsilon.emc.emf.EmfModel.loadModelFromUri[EmfModel.java:385]
	at org.eclipse.epsilon.emc.emf.EmfModel.loadModel[EmfModel.java:178]
	at org.eclipse.epsilon.eol.models.CachedModel.load[CachedModel.java:188]
	at org.hawk.ttc2018.Launcher.applyChanges[Launcher.java:184]
	at org.hawk.ttc2018.Launcher.applyChanges[Launcher.java:152]
	at org.hawk.ttc2018.Launcher.run[Launcher.java:139]
	at org.hawk.ttc2018.Launcher.main[Launcher.java:222]
Caused by: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '//@changes.5/@sourceChange/@addedElement/407640'. [file:/home/antonio/src/ttc2018liveContest/models/1/change10.xmi, 33, 297]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences[XMLHandler.java:1179]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.endDocument[XMLHandler.java:1264]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument[AbstractSAXParser.java:745]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument[XMLDocumentFragmentScannerImpl.java:510]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse[XML11Configuration.java:841]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse[XML11Configuration.java:770]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse[XMLParser.java:141]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse[AbstractSAXParser.java:1213]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse[SAXParserImpl.java:643]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse[SAXParserImpl.java:327]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load[XMLLoadImpl.java:175]
	... 10 more
Caused by: java.lang.IllegalArgumentException: The feature '07640' is not a valid feature
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eStructuralFeature[BasicEObjectImpl.java:733]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eObjectForURIFragmentSegment[BasicEObjectImpl.java:551]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject[ResourceImpl.java:766]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject[ResourceImpl.java:742]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences[XMLHandler.java:1160]
	... 20 more

org.eclipse.epsilon.eol.exceptions.models.EolModelLoadingException: Internal error: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Unresolved reference '//@changes.5/@sourceChange/@addedElement/407640'. [file:/home/antonio/src/ttc2018liveContest/models/1/change10.xmi, 33, 297]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.handleErrors[XMLLoadImpl.java:77]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load[XMLLoadImpl.java:185]
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad[XMLResourceImpl.java:261]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load[ResourceImpl.java:1518]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load[ResourceImpl.java:1297]
	at org.eclipse.epsilon.emc.emf.EmfModel.loadModelFromUri[EmfModel.java:385]
	at org.eclipse.epsilon.emc.emf.EmfModel.loadModel[EmfModel.java:178]
	at org.eclipse.epsilon.eol.models.CachedModel.load[CachedModel.java:188]
	at org.hawk.ttc2018.Launcher.applyChanges[Launcher.java:184]
	at org.hawk.ttc2018.Launcher.applyChanges[Launcher.java:152]
	at org.hawk.ttc2018.Launcher.run[Launcher.java:139]
	at org.hawk.ttc2018.Launcher.main[Launcher.java:222]
Caused by: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '//@changes.5/@sourceChange/@addedElement/407640'. [file:/home/antonio/src/ttc2018liveContest/models/1/change10.xmi, 33, 297]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences[XMLHandler.java:1179]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.endDocument[XMLHandler.java:1264]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument[AbstractSAXParser.java:745]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument[XMLDocumentFragmentScannerImpl.java:510]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse[XML11Configuration.java:841]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse[XML11Configuration.java:770]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse[XMLParser.java:141]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse[AbstractSAXParser.java:1213]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse[SAXParserImpl.java:643]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse[SAXParserImpl.java:327]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load[XMLLoadImpl.java:175]
	... 10 more
Caused by: java.lang.IllegalArgumentException: The feature '07640' is not a valid feature
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eStructuralFeature[BasicEObjectImpl.java:733]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eObjectForURIFragmentSegment[BasicEObjectImpl.java:551]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject[ResourceImpl.java:766]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject[ResourceImpl.java:742]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences[XMLHandler.java:1160]
	... 20 more

	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.handleErrors(XMLLoadImpl.java:77) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:185) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518) ~[org.eclipse.emf.ecore-2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297) ~[org.eclipse.emf.ecore-2.12.0.v20160420-0247.jar:na]
	at org.eclipse.epsilon.emc.emf.EmfModel.loadModelFromUri(EmfModel.java:385) ~[epsilon-1.5-emf-src.jar:na]
	at org.eclipse.epsilon.emc.emf.EmfModel.loadModel(EmfModel.java:178) ~[epsilon-1.5-emf-src.jar:na]
	at org.eclipse.epsilon.eol.models.CachedModel.load(CachedModel.java:188) ~[epsilon-1.5-core-src.jar:na]
	at org.hawk.ttc2018.Launcher.applyChanges(Launcher.java:184) ~[bin/:na]
	at org.hawk.ttc2018.Launcher.applyChanges(Launcher.java:152) ~[bin/:na]
	at org.hawk.ttc2018.Launcher.run(Launcher.java:139) ~[bin/:na]
	at org.hawk.ttc2018.Launcher.main(Launcher.java:222) ~[bin/:na]
Caused by: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Unresolved reference '//@changes.5/@sourceChange/@addedElement/407640'. (file:/home/antonio/src/ttc2018liveContest/models/1/change10.xmi, 33, 297)
	... 12 common frames omitted
Caused by: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '//@changes.5/@sourceChange/@addedElement/407640'. (file:/home/antonio/src/ttc2018liveContest/models/1/change10.xmi, 33, 297)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences(XMLHandler.java:1179) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.endDocument(XMLHandler.java:1264) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:745) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[na:1.8.0_102]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327) ~[na:1.8.0_102]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	... 10 common frames omitted
Caused by: java.lang.IllegalArgumentException: The feature '07640' is not a valid feature
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eStructuralFeature(BasicEObjectImpl.java:733) ~[org.eclipse.emf.ecore-2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eObjectForURIFragmentSegment(BasicEObjectImpl.java:551) ~[org.eclipse.emf.ecore-2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:766) ~[org.eclipse.emf.ecore-2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:742) ~[org.eclipse.emf.ecore-2.12.0.v20160420-0247.jar:na]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences(XMLHandler.java:1160) ~[org.eclipse.emf.ecore.xmi_2.12.0.v20160420-0247.jar:na]
	... 20 common frames omitted
```

**Comment by agarciadom** [comment]
This is now solved with the latest version - my naive batch solution works well now. Thanks!
