### ISSUE TITLE
High variability of batch Hawk variants' runtime causes timeout

### ISSUE THREAD

**Issue by marci543** [TransformationToolContest/ttc2018liveContest#102]
During runs in CI, batch Hawk variants (Hawk, HawkNeo4J, HawkSQLite) had very different runtimes which caused timeout in a few cases. Most often with HawkNeo4J.
This also happened on the server during benchmark.
See details at #101 and in the paper repo at `output/details/README.md#Remarks`, `output/details/output/log-2021-05-03T17.47.10.log`.
Once the timeout is reached by a tool on a query at a size, no further measurement is run on that model size or bigger sizes.

We should try to investigate the issue or change how timeout is handled.

**Comment by agarciadom** [comment]
I originally pegged this as a difference in the memory settings for Hawk, but after tweaking them to match our server builds (which doesn't hurt, anyway), I still ran into that timeout when running with sizes 1 and 2 (it took a while, though).

Looking at the case when it gets stuck, it gets stuck at zero CPU use. Using `jstack` on Hawk showed that the way in which we wait for Hawk to complete its synchronisation sometimes has the solution code waiting forever for it to happen:

```
root@ef3e2b89672c:/ttc/solutions/Hawk/org.hawk.ttc2018# jstack 15037
2021-05-06 23:07:02
Full thread dump OpenJDK 64-Bit Server VM (25.292-b10 mixed mode):

"Attach Listener" #17 daemon prio=9 os_prio=0 tid=0x00007f6ca4001000 nid=0x3b09 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-1-thread-1" #12 prio=5 os_prio=0 tid=0x00007f6d098f0000 nid=0x3adc waiting on condition [0x00007f6cb664f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006400b2a88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"EMF Reference Cleaner" #10 daemon prio=5 os_prio=0 tid=0x00007f6d09693000 nid=0x3ad9 in Object.wait() [0x00007f6cb706c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000006401f18d0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)

"main" #1 prio=5 os_prio=0 tid=0x00007f6d0800d000 nid=0x3ac0 waiting on condition [0x00007f6d0e8b8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007bf463c00> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:409)
	at org.hawk.ttc2018.StandaloneHawk.waitForSync(StandaloneHawk.java:144)
	at org.hawk.ttc2018.StandaloneHawk.waitForSync(StandaloneHawk.java:155)
	at org.hawk.ttc2018.AbstractLauncher.applyChanges(AbstractLauncher.java:224)
	at org.hawk.ttc2018.AbstractLauncher.run(AbstractLauncher.java:137)
	at org.hawk.ttc2018.BatchLauncher.main(BatchLauncher.java:106)
```

I need to investigate why this happens only very rarely in Hawk.

**Comment by agarciadom** [comment]
I think I have a fix for this: I'll try and rerun the batch solutions in Docker for sizes 1 and 2 and verify it works before doing an MR.

**Comment by marci543** [comment]
That's promising.
What are the "tools" affected which should be benchmarked again? Is it independent from the backend?

**Comment by agarciadom** [comment]
It's independent from the backend - it was a rare thread synchronisation issue. I'm afraid we might have to rerun all those that had timeouts to be sure. You can skip the configurations that had no timeouts, if that saves time.

**Comment by agarciadom** [comment]
@marci543 I've merged the branch after it passed CI.

I have been reviewing the latest results from the graph that @szarnyasg produced, and I think the race condition may have potentially impacted all Hawk solutions. Could you rerun all of them? Sorry for giving you more work :-(.
