### ISSUE TITLE
YAMTL build broken on Travis

### ISSUE THREAD

**Issue by agarciadom** [TransformationToolContest/ttc2018liveContest#38]
We told Travis to use Oracle JDK11, but the YAMTL build still fails with this:

```
Running benchmark: tool = EMFSolutionYAMTL, change set = 4, query = Q1
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ttc2018/LiveContestDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

@arturboronat can you look into this?

**Comment by agarciadom** [comment]
More details here:

https://travis-ci.org/TransformationToolContest/ttc2018liveContest/builds/585934868

**Comment by agarciadom** [comment]
Seems to be working now with Ubuntu Bionic in Travis:

https://travis-ci.org/TransformationToolContest/ttc2018liveContest/builds/585950791
